# Generated by Django 2.2.9 on 2020-01-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skincare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('star_ingredients', models.TextField(max_length=250)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('buy_again', models.CharField(max_length=10)),
                ('pros', models.TextField(max_length=250)),
                ('cons', models.TextField(max_length=250)),
            ],
        ),
    ]
