# Generated by Django 2.2.9 on 2020-01-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200122_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='skincare',
            name='star_ingredients',
        ),
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateField(verbose_name='Skin Status Date'),
        ),
    ]
