# Generated by Django 2.2.9 on 2020-01-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200123_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincare',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.Ingredient'),
        ),
    ]
