# Generated by Django 2.2.9 on 2020-01-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_skincare_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='details',
            field=models.TextField(default='No description', max_length=255),
        ),
    ]
