# Generated by Django 2.2.9 on 2020-01-23 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200123_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('skincare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Skincare')),
            ],
        ),
    ]
